eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #本地
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true


spring:
  redis:
    jedis:
      pool:
        max-active: 100
        max-wait: 10000
        min-idle: 1
        max-idle: 200
        minEvictableIdleTimeMillis: 60000
        numTestsPerEvictionRun: 3
        timeBetweenEvictionRunsMillis: 60000
    commandTimeout: 5000
    testOnBorrow: false
    testWhileIdle: false
    cluster:
      nodes: 134.175.131.249:7001,134.175.131.249:7002,134.175.131.249:7003,134.175.131.249:7004,134.175.131.249:7005,134.175.131.249:7006
      max-redirects: 3
    password: 123456
    database: 0
