server:
  port: 8429

spring:
  redis:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 47.102.219.201:7001
        - 47.102.219.201:7002
        - 47.102.219.201:7003
        - 47.102.219.201:7004
        - 47.102.219.201:7005
        - 47.102.219.201:7006
    password: 123456
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 60000


#spring:
#  redis:
#    port: 6379
#    host: 47.102.219.201
#    password: 123456
#    database: 0
#    timeout: 2000
#  application:
#    name: myself-Application

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #内网
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
